-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS flt_schema.portfolios
(
    portfolio_id serial NOT NULL,
    user_id integer,
    stock_id integer,
    quantity integer NOT NULL,
    average_price numeric(10, 2) NOT NULL,
    CONSTRAINT portfolios_pkey PRIMARY KEY (portfolio_id)
);

CREATE TABLE IF NOT EXISTS flt_schema.stockprices
(
    price_id serial NOT NULL,
    stock_id integer,
    price numeric(10, 2) NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    CONSTRAINT stockprices_pkey PRIMARY KEY (price_id)
);

CREATE TABLE IF NOT EXISTS flt_schema.stocks
(
    stock_id serial NOT NULL,
    symbol character varying(10) COLLATE pg_catalog."default" NOT NULL,
    company_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sector character varying(50) COLLATE pg_catalog."default",
    listed_on date,
    CONSTRAINT stocks_pkey PRIMARY KEY (stock_id),
    CONSTRAINT stocks_symbol_key UNIQUE (symbol)
);

CREATE TABLE IF NOT EXISTS flt_schema.transactions
(
    transaction_id serial NOT NULL,
    user_id integer,
    stock_id integer,
    transaction_type character varying(10) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS flt_schema.users
(
    user_id serial NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS flt_schema.portfolios
    ADD CONSTRAINT portfolios_stock_id_fkey FOREIGN KEY (stock_id)
    REFERENCES flt_schema.stocks (stock_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS flt_schema.portfolios
    ADD CONSTRAINT portfolios_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES flt_schema.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS flt_schema.stockprices
    ADD CONSTRAINT stockprices_stock_id_fkey FOREIGN KEY (stock_id)
    REFERENCES flt_schema.stocks (stock_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS flt_schema.transactions
    ADD CONSTRAINT transactions_stock_id_fkey FOREIGN KEY (stock_id)
    REFERENCES flt_schema.stocks (stock_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS flt_schema.transactions
    ADD CONSTRAINT transactions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES flt_schema.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;